#PBS -l select=1:ncpus=16:mem=64gb
#PBS -l walltime=48:00:00
#PBS -J 1-6

set -e
START_TIME=$SECONDS
module load anaconda3/personal

source activate gubbins_sim

cd /rds/general/user/jd2117/home/acba_legion_2024/gubbins_res

CLADE=$PBS_ARRAY_INDEX

if [ $CLADE -eq 1 ]
then
	cd "gc1_gubbins_ft_rax"
	OUT_NAME="gc1_gubbins_classified_snps.csv"
elif [ $CLADE -eq 2 ]
then
	cd gc2_gubbins_ft_raxml_128
	OUT_NAME="gc2_gubbins_classified_snps.csv"
else
	CLADE="clade_${CLADE}_gubbins_res"
	cd $CLADE 
	OUT_NAME="clade_${CLADE}_gubbins_classified_snps.csv"
fi

Rscript --vanilla ~/gubbins_testing/gubbins_sim/R/snp_classifier.R \
--reccy-gff *.recombination_predictions.gff \
--branch-base *embl_csv.csv --threads 16 \
--out $OUT_NAME

END_TIME=$(( SECONDS - START_TIME ))
END_DATE=$(date)
echo "Finished $OUT_NAME at $END_DATE in $END_TIME (s)"  >> ../ab_finished_snp_class.txt 

