#PBS -l select=1:ncpus=8:mem=64gb:cpu_type=rome
#PBS -l walltime=48:00:00
#PBS -J 1-3

set -e 
source /rds/general/user/jd2117/home/miniforge3/bin/activate gubbins_env
cd /rds/general/user/jd2117/ephemeral/
# Set up the current run id 
#CURRENT_DIR=$(head -n $PBS_ARRAY_INDEX ~/acinetobacter_ENA_download_2021_03_23/gubbins_runs | tail -n 1)
CLADE=$PBS_ARRAY_INDEX
#cd $CURRENT_DIR

ALN_FILE="/rds/general/user/jd2117/home/acba_legion_2024/ska_output/lp${CLADE}_ska2_aln.aln"
echo "This is the aln file: $ALN_FILE "
GUBB_DIR="lp${CLADE}_gubbins_res"
if [ -d $GUBB_DIR ]
then
	rm -r $GUBB_DIR
	mkdir $GUBB_DIR
else
	mkdir $GUBB_DIR
fi

cd $GUBB_DIR
START_GUB=$SECONDS
/usr/bin/time -v run_gubbins.py --prefix $GUBB_DIR \
--use-time-stamp --threads 8 \
--verbose --tree-builder raxml --first-tree-builder fasttree \
--min-snps 2 \
$ALN_FILE > gubbins_log 2>&1
END_GUB=$(( SECONDS - START ))
PROC=$(cat /proc/cpuinfo | grep 'model name' | uniq)
echo "Took this long for clade $CLADE run, $END_GUB " > "lp${CLADE}_time.txt"
echo "Used this processor for the runs: $PROC" >> "lp${CLADE}_time.txt"

source /rds/general/user/jd2117/home/anaconda3/bin/activate gubbins_sim

python ~/gubbins_testing/gubbins_sim/python/embl_changer.py --embl *branch_base_reconstruction.embl \
--output "lp${CLADE}.embl_csv" --threads 8 

echo "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"
echo "@@@@@@@@@@@@@@@@@@ DONE @@@@@@@@@@@@@@@@@@@@@@@@@"
echo "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"
