#PBS -l select=1:ncpus=32:mem=124gb
#PBS -l walltime=72:00:00

set -e 
module load anaconda3/personal

source activate gubbins2_env

cd ~/acinetobacter_ENA_download_2021_03_23/gubbins_runs/gc2_5092_gubbins

python ~/gubbins/python/run_gubbins.py --prefix gc2_gubbins --use-time-stamp --threads 32 \
--verbose --tree-builder iqtree --first-tree-builder iqtree --mar --model JC \
../gc2_5092_splits/gc2_5092_ska_aln.aln 

echo "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"
echo "@@@@@@@@@@@@@@@@@@ DONE @@@@@@@@@@@@@@@@@@@@@@@@@"
echo "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"
