#PBS -l select=1:ncpus=128:mem=256gb:cpu_type=rome
#PBS -l walltime=72:00:00

set -e 
source /rds/general/user/jd2117/home/miniforge3/bin/activate gubbins_env

cd /rds/general/user/jd2117/ephemeral/

if [ -d gc2_gubbins_ft_raxml_128 ]
then
	rm -r gc2_gubbins_ft_raxml_128
	mkdir gc2_gubbins_ft_raxml_128
else
	mkdir gc2_gubbins_ft_raxml_128
fi

#cd ~/acinetobacter_ENA_download_2021_03_23/gubbins_runs/gc2_5092_fasttree_iqtree_gubbins
GUBB_EXC="/rds/general/user/jd2117/home/acba_legion_2024/gubbins/python/run_gubbins.py"

cd ./gc2_gubbins_ft_raxml_128
START=$SECONDS
/usr/bin/time -v ${GUBB_EXC} --prefix gc2_gubbins --use-time-stamp \
--threads 128 --verbose --tree-builder raxml --first-tree-builder fasttree \
--max-window-size 100000 --min-snps 2 \
/rds/general/user/jd2117/home/acba_legion_2024/ska_output/gc2_5092_trimmed_ska2_aln.aln > gubbins_log 2>&1 
END=$(( SECONDS - START ))
PROC=$(cat /proc/cpuinfo | grep 'model name' | uniq)
echo "Took this long for GC2 run, $END_GUB" > "./GC2_time.txt"
echo "Used this processor for the runs: $PROC" >> "./GC2_time.txt"

source /rds/general/user/jd2117/home/anaconda3/bin/activate gubbins_sim

python ~/gubbins_testing/gubbins_sim/python/embl_changer.py --embl *branch_base_reconstruction.embl \
--output "gc2_gubbins.embl_csv" --threads 32 

echo ""
echo "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"
echo "@@@@@@@@@@@@@@@@@@ DONE @@@@@@@@@@@@@@@@@@@@@@@@@"
echo "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"
echo ""

