#PBS -l select=1:ncpus=32:mem=124gb
#PBS -l walltime=72:00:00

set -e 
module load anaconda3/personal

source activate gubbins_git_3.2.1

cd /rds/general/user/jd2117/ephemeral/

if [ -d gc1_gubbins_3.2.1_ft_rax ]
then
	rm -r gc1_gubbins_3.2.1_ft_rax
	mkdir gc1_gubbins_3.2.1_ft_rax
else
	mkdir gc1_gubbins_3.2.1_ft_rax
fi

#cd ~/acinetobacter_ENA_download_2021_03_23/gubbins_runs/gc2_5092_fasttree_iqtree_gubbins

cd ./gc1_gubbins_3.2.1_ft_rax

/usr/bin/time -v python ~/gubbins_acba_legion/gubbins/python/run_gubbins.py --prefix gc1_gubbins \
--use-time-stamp --threads 32 \
--verbose --tree-builder raxml --first-tree-builder fasttree \
--max-window-size 100000 --min-snps 2 \
~/acinetobacter_ENA_download_2021_03_23/gubbins_runs/gc1_ska_aln.aln > gubbins_log 2>&1
PROC=$(cat /proc/cpuinfo | grep 'model name' | uniq)
echo "Took this long for GC1 run, $END_GUB" > "./GC2_time.txt"
echo "Used this processor for the runs: $PROC" >> "./GC2_time.txt"
python ~/gubbins_testing/gubbins_sim/python/embl_changer.py --embl *branch_base_reconstruction.embl \
--output "gc1_gubbins.embl_csv" --threads 12 

echo ""
echo "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"
echo "@@@@@@@@@@@@@@@@@@ DONE @@@@@@@@@@@@@@@@@@@@@@@@@"
echo "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"
echo ""

