#PBS -l select=1:ncpus=20:mem=240gb
#PBS -l walltime=48:00:00

set -e 
module load anaconda3/personal

source activate gubbins2_env

cd /rds/general/user/jd2117/ephemeral/

if [ -d gc2_gubbins_3.1.14 ]
then
	rm -r gc2_gubbins_3.1.14
	mkdir gc2_gubbins_3.1.14
else
	mkdir gc2_gubbins_3.1.14
fi

#cd ~/acinetobacter_ENA_download_2021_03_23/gubbins_runs/gc2_5092_fasttree_iqtree_gubbins

cd ./gc2_gubbins_3.1.14

/usr/bin/time -v python ~/gubbins/python/run_gubbins.py --prefix gc2_gubbins --use-time-stamp --threads 20 \
--verbose --tree-builder iqtree --first-tree-builder fasttree --model JC \
--max-window-size 100000 \
~/acinetobacter_ENA_download_2021_03_23/gubbins_runs/gc2_5092_splits/gc2_5092_ska_aln.aln 

echo ""
echo "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"
echo "@@@@@@@@@@@@@@@@@@ DONE @@@@@@@@@@@@@@@@@@@@@@@@@"
echo "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"
echo ""

