#PBS -l select=1:ncpus=16:mem=124gb
#PBS -l walltime=72:00:00

set -e 
module load anaconda3/personal

source activate gubbins2_env

cd /rds/general/user/jd2117/ephemeral/

if [ -d gc2_gubbins_3.1.14_mar_16 ]
then
	rm -r gc2_gubbins_3.1.14_mar_16
	mkdir gc2_gubbins_3.1.14_mar_16
else
	mkdir gc2_gubbins_3.1.14_mar_16
fi

#cd ~/acinetobacter_ENA_download_2021_03_23/gubbins_runs/gc2_5092_fasttree_iqtree_gubbins

cd ./gc2_gubbins_3.1.14_mar_16

python ~/gubbins/python/run_gubbins.py --prefix gc2_gubbins --use-time-stamp --threads 16 \
--verbose --tree-builder iqtree --mar --first-tree-builder fasttree --model JC \
--max-window-size 100000 \
~/acinetobacter_ENA_download_2021_03_23/gubbins_runs/gc2_5092_splits/gc2_5092_ska_aln.aln > output_info 2>&1

echo ""
echo "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"
echo "@@@@@@@@@@@@@@@@@@ DONE @@@@@@@@@@@@@@@@@@@@@@@@@"
echo "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"
echo ""

