#PBS -l select=1:ncpus=32:mem=124gb
#PBS -l walltime=72:00:00

set -e 
module load anaconda3/personal

source activate gubbins_git

cd /rds/general/user/jd2117/ephemeral/

if [ -d lp1_gubbins_3.1.14_ft_iqt_32 ]
then
	rm -r lp1_gubbins_3.1.14_ft_iqt_32
	mkdir lp1_gubbins_3.1.14_ft_iqt_32
else
	mkdir lp1_gubbins_3.1.14_ft_iqt_32
fi

#cd ~/acinetobacter_ENA_download_2021_03_23/gubbins_runs/gc2_5092_fasttree_iqtree_gubbins

cd ./lp1_gubbins_3.1.14_ft_iqt_32

/usr/bin/time -v python ~/gubbins/python/run_gubbins.py --prefix lp1_gubbins --use-time-stamp --threads 32 \
--verbose --tree-builder iqtree --first-tree-builder fasttree --model JC \
--max-window-size 100000 \
~/legionella_work/ska_runs/legion_1_ska_aln.aln 

echo ""
echo "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"
echo "@@@@@@@@@@@@@@@@@@ DONE @@@@@@@@@@@@@@@@@@@@@@@@@"
echo "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"
echo ""

