#PBS -l select=1:ncpus=1:mem=2gb
#PBS -l walltime=24:00:00
#PBS -J 1-3

set -e 
START_TIME=$SECONDS
module load anaconda3/personal

source activate gubbins_git 

cd ~/legionella_work/gubbins

CURRENT_CLADE=$PBS_ARRAY_INDEX

## Lets run the SNP classifier first 
GUBBINS_RES="lp${CURRENT_CLADE}_gubbins"
cd $GUBBINS_RES


RECCY_FILE="${GUBBINS_RES}.recombination_predictions.gff"
BRANCH_BASE="${GUBBINS_RES}_embl_csv.csv"
SNP_FILE="${GUBBINS_RES}_classified_snps.csv"

Rscript --vanilla ~/gubbins_testing/gubbins_sim/R/snp_classifier.R \
--reccy-gff $RECCY_FILE --branch-base $BRANCH_BASE --out $SNP_FILE
END_TIME=$(( SECONDS - START_TIME ))
END_DATE=$(date)
echo "Finished $GUBBINS_RES at $END_DATE in $END_TIME (s)"  >> ../lp_finished_snp_class.txt 

## Lets run the pastml now 
#TREE_FILE="${CURRENT_GPSC}.node_labelled.final_tree.tre"
#STATE_FILE="${CURRENT_GPSC}_states.tsv"
#STATES_RECON="${CURRENT_GPSC}_tag_recon.tsv"

#python ~/gubbins_testing/gubbins_sim/python/testing_pastml.py --gubbins $TREE_FILE \
#--out_prefix $STATES_RECON --data $STATE_FILE


