#PBS -l select=1:ncpus=1:mem=24gb
#PBS -l walltime=12:00:00

set -e 

module load anaconda3/personal

source activate ska_runs

cd /rds/general/user/jd2117/ephemeral/clade_4_skf_files

ska map -c -o clade_4_aln -m -r clade_4_ref *.skf

echo "#########################################################################"
echo ""
echo "                                   DONE                                  "
echo ""
echo "#########################################################################"
