#PBS -l select=1:ncpus=8:mem=16gb
#PBS -l walltime=24:00:00
#PBS -J 1-3

set -e

module load anaconda3/personal

source activate gubbins_sim

cd ~/legionella_work/gubbins/theses_results

CLADE=$PBS_ARRAY_INDEX
cd "lp${CLADE}_gubbins_3.2.0_ft_raxml_32"
OUT_NAME="lp${CLADE}_gubbins_classified_snps.csv"

Rscript --vanilla ~/gubbins_testing/gubbins_sim/R/snp_classifier.R \
--reccy-gff *.recombination_predictions.gff \
--branch-base *embl_csv.csv --threads 8 \
--out $OUT_NAME


