#PBS -l select=1:ncpus=1:mem=2gb
#PBS -l walltime=02:00:00
## Script to run SKA 2 on the Imperial HPC for the acba gc2 lineage

source /rds/general/user/jd2117/home/anaconda3/bin/activate bioperl

cd /rds/general/user/jd2117/ephemeral/acba_legion/trimmed_assemblies

START_TIME=$SECONDS
cd lp1_trimmed

bash ~/acba_legion_2024/ab_lp_work/bash/trim_smaller_contigs.sh cluster_1*.txt

cd ../lp2_trimmed

bash ~/acba_legion_2024/ab_lp_work/bash/trim_smaller_contigs.sh cluster_2*.txt

cd ../lp3_trimmed 
bash ~/acba_legion_2024/ab_lp_work/bash/trim_smaller_contigs.sh cluster_3*.txt

END_TIME=$(( SECONDS - START_TIME ))
datio=$(date)
echo "Finished in ${END_TIME} at $datio "

